import pandas as pd
import numpy as np

# Stats we want to build rolling features for
ROLLING_STATS = ['points', 'rebounds', 'assists', 'steals', 'blocks', 'minutes', 'turnovers']
WINDOWS       = [5, 10]

# get rolling averages
def add_rolling_averages(df: pd.DataFrame) -> pd.DataFrame:
    """Add rolling average features per player. Uses shift(1) to prevent data leakage."""
    df = df.copy()
    for stat in ROLLING_STATS:
        if stat not in df.columns:
            continue
        grp = df.groupby('playerid')[stat]
        for w in WINDOWS:
            df[f'{stat}_avg{w}'] = grp.transform(
                lambda x: x.shift(1).rolling(w, min_periods=1).mean()
            )
        # Season average up to but not including current game
        df[f'{stat}_avg_season'] = grp.transform(
            lambda x: x.shift(1).expanding(min_periods=1).mean()
        )
    return df

# add days of rest as a feature
def add_rest_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add days of rest and back-to-back flag."""
    df = df.copy()
    df['days_rest'] = (
        df.groupby('playerid')['date']
        .diff()
        .dt.days - 1
    ).clip(0, 14)  # cap at 14 days
    df['is_back_to_back'] = (df['days_rest'] == 0).astype(int)
    return df

# add home vs away as a feature
def add_game_context(df: pd.DataFrame) -> pd.DataFrame:
    """Add home/away and result encoding."""
    df = df.copy()
    df['is_home'] = (df['homeaway'].str.strip() == 'H').astype(int)
    return df

# not currently being used
def add_opponent_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add opponent defensive averages — how many points/reb/ast does this
    opponent typically allow? Computed from the same dataset so it's always
    available without needing a separate table.
    Uses shift to avoid leakage.
    """
    df = df.copy()
    df['opponent'] = df['opponent'].str.strip()

    for stat in ['points', 'rebounds', 'assists']:
        if stat not in df.columns:
            continue
        # Average allowed by each opponent up to that date
        opp_avg = (
            df.groupby(['opponent', 'season'])[stat]
            .transform(lambda x: x.shift(1).expanding(min_periods=1).mean())
        )
        df[f'opp_{stat}_allowed_avg'] = opp_avg

    return df

# run all the feature creation functions
def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """Run all feature engineering steps in order."""
    print("Engineering features...")
    df = add_rolling_averages(df)
    df = add_rest_features(df)
    df = add_game_context(df)
    df = add_opponent_features(df)
    print(f"Feature engineering complete. Shape: {df.shape}")
    return df

# get feature columns
def get_feature_cols(stat: str = 'points') -> list[str]:
    """Return the list of feature columns to use for a given stat."""
    base = [
        f'{stat}_avg5',
        f'{stat}_avg10',
        f'{stat}_avg_season',
        'minutes_avg5',
        'minutes_avg10',
        'days_rest',
        'is_back_to_back',
        'is_home',
        f'opp_{stat}_allowed_avg',
    ]
    return [col for col in base if col in get_all_possible_cols()]

# get all possible features
def get_all_possible_cols() -> list[str]:
    """All columns that could be generated by engineer_features."""
    cols = []
    for stat in ROLLING_STATS:
        for w in WINDOWS:
            cols.append(f'{stat}_avg{w}')
        cols.append(f'{stat}_avg_season')
    cols += ['days_rest', 'is_back_to_back', 'is_home']
    for stat in ['points', 'rebounds', 'assists']:
        cols.append(f'opp_{stat}_allowed_avg')
    return cols